# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Getting Started Programatically' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Getting Started Programatically
  pod 'InstantSearch-Swift', '~> 1.0.0-beta1'
  
end
