# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Getting Started Storyboard Objc' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'InstantSearch', '~> 2.0'
  # Pods for Getting Started Storyboard Objc
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.1'
    end
  end
end
