# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoDirectory' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'InstantSearch', '~> 5.0.0'
  pod 'SDWebImage'
  pod 'TagListView', '~> 1.0'
  pod 'WARangeSlider'

  # Pods for DemoDirectory

  target 'DemoDirectoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
