# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target ‘BasicDemo’ do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'InstantSearch-Core-Swift', :path => ‘../../instantsearch-core-swift’
  pod 'AlgoliaSearch-Client-Swift', :path => ‘../../algoliasearch-client-swift’
  pod 'InstantSearch', :path => '/Users/guydaher/Developer/Algolia/iOS/instantsearch-ios'
  pod 'AFNetworking', '~> 3.0'

end
