# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
def testing_pods
  pod 'Quick'
  pod 'Nimble'
end

target 'IS-CustomSource' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'InstantSearch', '~> 2.0'
  pod 'AFNetworking', '~> 3.0'
  pod 'Nuke'
  pod 'Alamofire', '~> 4.7'
  # Pods for Icebnb

end
