# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ecommerce' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'InstantSearch-Core-Swift', '~> 1.0'

  # Pods for ecommerce

  target 'ecommerceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ecommerceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
