# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Getting Started Storyboard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Getting Started Storyboard
  pod 'InstantSearch-iOS', :git => 'https://github.com/algolia/instantsearch-ios.git', :branch => 'multi-index'
  pod 'InstantSearch-Core-Swift', :git => 'https://github.com/algolia/instantsearch-core-swift.git', :branch => 'develop'

end
