# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Query Suggestions' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  inhibit_all_warnings!
  
  # Pods for Query Suggestions
  pod 'InstantSearch-iOS', '~> 2.0'
  pod 'AFNetworking', '~> 3.0'

end
