# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movies' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movies
  pod 'InstantSearch-iOS', :git => 'https://github.com/algolia/instantsearch-ios.git', :branch => 'multi-index'
  pod 'InstantSearch-Core-Swift', :git => 'https://github.com/algolia/instantsearch-core-swift.git', :branch => 'develop'
  pod 'AFNetworking', '~> 3.0'
  
  inhibit_all_warnings!

end
